# user must logged in here and then can create notes , after loggging proccess
# he/she can have access and refresh token 
POST http://127.0.0.1:8000/api/token/  HTTP/1.1 
Content-Type: application/json

{
    "username": "vasiko",
    "password": "vasiko12345"
}
###

# he/she can refresh acces token with here to copy refresh token and place here 
POST http://127.0.0.1:8000/api/token/refresh/  HTTP/1.1 
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NjE2MjYwMiwiaWF0IjoxNzQ2MDc2MjAyLCJqdGkiOiJkNDZjYzQyZmNiZmQ0YjhmODQ0MjI3ZGJlZjAxMjJhYSIsInVzZXJfaWQiOjF9.R5pwmZgzBP_RRNINyfA4N1Jmm07oiIzSB7AULIWFBT0"
}
###

# get all notes, which user have, (not users, only user which is logged in )
GET http://127.0.0.1:8000/api/notes/ HTTP/1.1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDc5MTI3LCJpYXQiOjE3NDYwNzczMjcsImp0aSI6IjA1MDUyZjVjMGE5NDQ5MWI4YWMxMGUzMjk2MGNhZDU5IiwidXNlcl9pZCI6Mn0.18IKh7OP11LMFPNiLhDpAe97SpbZLnHeMDWXvC4W9oM
###

# get single note
GET http://127.0.0.1:8000/api/notes/c2a55623-7a8e-4099-a0e0-21465d85a99e/ HTTP/1.1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDc4NzM0LCJpYXQiOjE3NDYwNzY5MzQsImp0aSI6IjFmOWY1YTk3OGNjODRkMTFiNWE5MDliNDUwOWU4ODIwIiwidXNlcl9pZCI6MX0.CW_hlSBic9Pg2p38PzLr2TxctStA4b0IU8mYEvMHaAA

###

# if user is logged in and has access token , he/she can post the note 
POST http://127.0.0.1:8000/api/notes/ HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDc4NzM0LCJpYXQiOjE3NDYwNzY5MzQsImp0aSI6IjFmOWY1YTk3OGNjODRkMTFiNWE5MDliNDUwOWU4ODIwIiwidXNlcl9pZCI6MX0.CW_hlSBic9Pg2p38PzLr2TxctStA4b0IU8mYEvMHaAA

{
    "content": "content next next 2",
    "author": 1
}
###

# updata note
PUT  http://127.0.0.1:8000/api/notes/fbe8fc7d-e6c9-4044-a34f-75849b446348/ HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDc4NzM0LCJpYXQiOjE3NDYwNzY5MzQsImp0aSI6IjFmOWY1YTk3OGNjODRkMTFiNWE5MDliNDUwOWU4ODIwIiwidXNlcl9pZCI6MX0.CW_hlSBic9Pg2p38PzLr2TxctStA4b0IU8mYEvMHaAA

{
  "content": "content next next second",
    "author": 1
}
###

# DELETE note 
DELETE  http://127.0.0.1:8000/api/notes/fbe8fc7d-e6c9-4044-a34f-75849b446348/ HTTP/1.1 